// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarWatch6.Data;

#nullable disable

namespace SolarWatch6.Migrations
{
    [DbContext(typeof(SolarWatchContext))]
    [Migration("20230906125917_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarWatch6.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "London",
                            Country = "UK",
                            Lat = 51.509864999999998,
                            Lon = -0.118092
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Budapest",
                            Country = "HU",
                            Lat = 47.497912999999997,
                            Lon = 19.040236
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Paris",
                            Country = "FR",
                            Lat = 48.864716000000001,
                            Lon = 2.3490139999999999
                        });
                });

            modelBuilder.Entity("SolarWatch6.Models.SunsetSunriseData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Sunrise")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Sunset")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("SunsetSunriseDataCollection");
                });

            modelBuilder.Entity("SolarWatch6.Models.SunsetSunriseData", b =>
                {
                    b.HasOne("SolarWatch6.Models.City", "City")
                        .WithMany("SunsetSunriseDataList")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SolarWatch6.Models.City", b =>
                {
                    b.Navigation("SunsetSunriseDataList");
                });
#pragma warning restore 612, 618
        }
    }
}
